[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "dotnet BlazorServerStarter.dll"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100